apiVersion: apps/v1
kind: Deployment
metadata:
  name: nocommerce
spec:
  selector:
    matchLabels:
      run: nocommerce
  replicas: 1
  template:
    metadata:
      labels:
        run: nocommerce
    spec:
      containers:
      - name: nocommerce
        image: eu.gcr.io/devsecops-demo-324812/devsecops
        ports:
        - containerPort: 80
