name: DAST
'on':
  push:
    branches:
      - developer
  pull_request:
    branches:
      - developer
  workflow_dispatch: null
  
jobs:
   DAST_Zap:
    name: DAST Zap
    runs-on: ubuntu-latest 
    steps:
     - name: zap-Scan
       uses: zaproxy/action-baseline@v0.4.0
       with:
        target: http://a3f8efd59f337478381772b2084a881f-969196202.ap-southeast-2.elb.amazonaws.com
     - name: artifacts
       uses: actions/upload-artifact@v2
       with:
          name: DAST-artifact
          path: ${{ github.workspace }}
