name: DevSecOps-test
'on':
  push:
    branches:
      - developer
  pull_request:
    branches:
      - developer
  workflow_dispatch: null

jobs:

  Build_Image_Docker_Test:
    name: Build-Push-Image-Docker
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - uses: mr-smithers-excellent/docker-build-push@v5
        name: Build & push Docker image
        with:
          image: kumardineshwar/devsecops
          tags: 
          - 'v1'
          - 'latest'
          - '${{ github.sha }}'
          registry: docker.io
          dockerfile: ./Dockerfile
          username: '${{ secrets.DOCKER_USERNAME }}'
          password: '${{ secrets.DOCKER_PASSWORD }}'
      
      - run: echo "Pushed image to docker.io/kumardineshwar/ $GITHUB_REF"     


