name: DevSecOps-test
'on':
  push:
    branches:
      - developer
  pull_request:
    branches:
      - developer
  workflow_dispatch: null

jobs:

  Build_Image_Docker_Test:
      name: Build-Push-Image-Docker
      runs-on: ubuntu-latest
      steps:
        - name: 'Build, tag, and push image to docker.io'
          env:
            IMAGE_TAG: '${{ github.sha }}'
          run: |
            docker build -t kumardineshwar/devsecops:$IMAGE_TAG .
            docker push kumardineshwar/devsecops:$IMAGE_TAG     
        - name: Checkout
          uses: actions/checkout@v2
        - uses: mr-smithers-excellent/docker-build-push@v5
          name: Build & push Docker image
          with:
            image: kumardineshwar/devsecops
            tags: 'v1, latest'
            registry: docker.io
            dockerfile: ./Dockerfile
            username: '${{ secrets.DOCKER_USERNAME }}'
            password: '${{ secrets.DOCKER_PASSWORD }}'
